### ISSUE TITLE
Cannot access IKS web terminal

### ISSUE THREAD

**Issue by ogaye-ibm** [ibm-garage-cloud/planning#1]
**Describe the bug**
On the IKS cluster, I cannot access to the web terminal
**To Reproduce**
1. From the main cluster anding/home page, click on "Web terminal"
2. When prompted with "Install Kubernetes Terminal", click on "Install"
3. You will get a "Not authorized" message

**Expected behavior**
Terminal installed and accessible

**Screenshots**
Attached (3)

**IBM Cloud**
Select the services and tools affected
- [ X] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - NA

**Additional context**
NA

**Comment by ogaye-ibm** [comment]
![mooc-iks-web-console-1](https://user-images.githubusercontent.com/56206659/68769106-c5ae1980-05f1-11ea-8e98-35c71190ac9a.png)
![mooc-iks-web-console-2](https://user-images.githubusercontent.com/56206659/68769107-c5ae1980-05f1-11ea-8277-46081e45c98a.png)
![mooc-iks-web-console-3](https://user-images.githubusercontent.com/56206659/68769109-c5ae1980-05f1-11ea-8708-2fcc911af75d.png)

**Comment by mjperrins** [comment]
This was not a pre-req for the course, so have not installed this on the MOOC clusters.
