### ISSUE TITLE
Chore: Add Contributing link as a first-level item in the Developer Guide menu (and refresh content)

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#101]

**Comment by mjperrins** [comment]
@bwoolf1 have made this change in `ocp43` branch , this will need your eyes on it, the guidance is keep it short and sweet :-) The Carbon team have a lot of material, just for reference https://www.carbondesignsystem.com/how-to-contribute/overview

**Comment by mjperrins** [comment]
Look for some inspiration from this contributing page, nice and simple 

https://ocp42.cloudpak8s.io/

**Comment by bwoolf1** [comment]
Is this issue complete? ibm-garage-cloud/ibm-garage-developer-guide#89 updated `ibm-garage-developer-guide/src/pages/contributing/`. ibm-garage-cloud/ibm-garage-developer-guide#92 added the "Edit this page on GitHub" link to the bottom of each page. Is there anything else to do?
