### ISSUE TITLE
Multicluster support: Remove dependency on hardcoded domain names in deployment objects

### ISSUE THREAD

**Issue by kipharris** [ibm-garage-cloud/planning#117]
The node / Typescript starter kit defines one or more variables which represent the DNS domain name of the target cluster. These variables are required by the Ingress definition and (i think) the Swagger UI console. The developer must provide values for these variables prior to the Helm/Tiller template processing (which happens during deployment). This approach, however, is not compatible with a multi-cloud environment.  For example, if IBM MCM is managing a dynamic assignment of the application among multiple target clusters, the domain name for the application isn't known in advance and can change even following deployment.

The starter kit needs to be updated to remove this dependency on a Developer or a DevOps SRE to set this value manually.

Planning issue https://github.com/ibm-garage-cloud/planning/issues/36 is an earlier iteration which sought to address this need.

**Comment by mjperrins** [comment]
@seansund what is the status on this issues ? is this completed as well
