### ISSUE TITLE
igc namespace command 

### ISSUE THREAD

**Issue by lsteck** [ibm-garage-cloud/planning#120]
As of igc version 0.4.0 the igc namespace command isn't working.

I am using OpenShift 4.3 but I don't think that is the issue.

1. verify correct version
17:37 $ igc --version
0.4.0

2. This is the documented usage that doesn't work
17:49 $ igc namespace -n dev2-test
Checking for existing namespace: undefined

3. This used to work
17:49 $ igc namespace dev-test
Checking for existing namespace: undefined

4. This command does work
17:49 $ igc namespace --namespace dev-test
Checking for existing namespace: dev-test

**Expected behavior**
Namespace on OCP 4.3 should be created

**Desktop (please complete the following information):**
Mac OS Catalina

**Comment by seansund** [comment]
Run `oc new project` under the covers of `igc namespace` if on openshift

**Comment by seansund** [comment]
Common library for validation of kubernetes resource names

**Comment by seansund** [comment]
@lsteck Just realized you are using the deprecated version of the CLI as well. Follow the instructions under the `Install the CLI` accordian - https://cloudnativetoolkit.dev/getting-started/cli/
