### ISSUE TITLE
Dashboard tab and page labeled Starter Kits, not Code Patterns

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#121]
Labels on the Dashboard that say Starter Kits need to be changed to say Code Patterns.

The Dashboard has three tabs: Dashboard, Activation, and Starter Kits. The label on the third tab should be updated.

The title of the Starter Kits notebook page is Starter Kit Templates. This should be updated to Code Patterns.

**Comment by bwoolf1** [comment]
Also, the dashboard's label says Development Dashboard. It should really say Developer Dashboard, to go with Developer Environment.

**Comment by mjperrins** [comment]
This is now resolved in latest Dashboard build
