### ISSUE TITLE
Dashboard on IKS link to Web Console for Kubernetes is not working

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#147]
**Describe the bug**
Dashboard on IKS link to Web Console for Kubernetes is not working

WEB_CONSOLE: https://c2.us-east.containers.cloud.ibm.com:20924/console

**To Reproduce**
1. open `igc dashboard` on IKS cluster'
2. Click WEB_CONSOLE Link
3. Security issue

**Expected behavior**
Should open the Kubernetes Console 

- [X ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by seansund** [comment]
This is a duplicate of #91
