### ISSUE TITLE
ARTIFACTORY_ENCRYPT is still spelt wrong on IKS install 

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#151]
**Describe the bug**
ARTIFACTORY_ENCRYPT is still spelt wrong on IKS install 

**To Reproduce**
1. Install iteration zero to green on IKS
2. check secret `tools->artifcactory-acess`
3. see that secret is spelt wrong and will not match Jenkins and Tekton pipelines

**Expected behavior**
Spelling is corrected to be inline with OCP installs

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [X] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**

**Additional context**

**Comment by seansund** [comment]
The value is spelled correctly in the environment I just set up - 

<img width="308" alt="Screen Shot 2020-03-15 at 10 52 41 PM" src="https://user-images.githubusercontent.com/3800123/76721950-beb62580-670f-11ea-8140-6e312f7a542d.png">
