### ISSUE TITLE
Maureen would like to be able to do a sonarscan on her application without requiring extra sonarqube setup in the repository

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#155]
Right now, the sonarscan step in the build pipelines expect very specific logic in the project to exist in order for the scan to run.

We should generalize that logic into the pipeline so that the scan can run on any project.

We can use this image - `sonarsource/sonar-scanner-cli`

Also remove sonarscan libraries from templates (may still need sonarscan.properties)

**Comment by lsteck** [comment]
@seansund I was thinking maybe we should leave the sonar scan libraries in the templates.  It enables the developers to run them locally when developing their code and see if there are any issues and check on code coverage before checking it in.  What do you think?

**Comment by mjperrins** [comment]
@lsteck I agree supporting local scanning is a positive step
