### ISSUE TITLE
Enable Developer.com Java Spring code pattern with igc enable

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#178]
https://github.com/IBM/java-spring-app

Verify on all 3 platforms:
- [x] IKS
- [ ] OCP3
- [x] OCP4

Verify with both pipelines:
- [x] Jenkins
- [x] Tekton

**Comment by lsteck** [comment]
@seansund 

Using our garage-dev-iks-cluster on Kedar's account.
Running 
igc --version
0.4.12
I'm getting 403 forbidden error
> igc namespace dev-lds-jenkins --jenkins
Setting up namespace dev-lds-jenkins and serviceAccount default
~/2020/git/ibmgaragecloud/igc_enable/java-spring-app[development|✔]
> igc pipeline -n dev-lds-jenkins --jenkins
Creating secret(s) with git credentials
  Project git repo: https://github.com/lsteck/java-spring-app.git
? Provide the username: lsteck
? Provide your password/personal access token: [hidden]
? Provide the branch the pipeline should use: development
Registering pipeline: lsteck.java-spring-app.development
Error creating folder
(node:87164) UnhandledPromiseRejectionWarning: Error: Forbidden

I see: <body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>\n'

I tried the same thing using OUR Java template and get the same error.

**Comment by lsteck** [comment]
And it looks like the in the Basic Auth is set in the header properly with the Jenkins user and apitoken

**Comment by seansund** [comment]
Try v0.4.13 of the cli. There was a different bug I just fixed

**Comment by lsteck** [comment]
FYI, have a PR for this fix and tied it to issue #242 .

**Comment by lsteck** [comment]
@seansund 

I see that with ibmcloud-dev version of v1.0.9 - removes autologin for ibmcloud
But I'm getting authentication failed errors in my pipeline.  Are we supposed to add that logic into our pipelines now?

**Comment by lsteck** [comment]
I'm having problems with the java-spring-app on OCP 4.3 with both Jenkins and Tekton.  Both 
 fail during the build step  when buidah tries to build the docker container.  I've made sure the privileged SCC is applied to the service account for Jenkins and Tekton and we have the securityContest: privileged: true
 

`Selecting previously unselected package multiarch-support.
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 4384 files and directories currently installed.)
Preparing to unpack .../multiarch-support_2.27-3ubuntu1_amd64.deb ...
Unpacking multiarch-support (2.27-3ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/multiarch-support_2.27-3ubuntu1_amd64.deb (--unpack):
 error setting timestamps of '/usr/share/doc/multiarch-support/changelog.Debian.gz.dpkg-new': Permission denied
Errors were encountered while processing:
 /var/cache/apt/archives/multiarch-support_2.27-3ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
subprocess exited with status 100
subprocess exited with status 100
error building at STEP "RUN apt-get update && apt-get install -y maven": exit status 100
`

**Comment by lsteck** [comment]
The buildah build works fine on IKS using the current Dockerfile.

**Comment by lsteck** [comment]
Apparently there are some know issues with Buildah on a NFS file system.  From what I can tell we are using NFS. IBM Cloud also supports ext4 so maybe we should try that https://cloud.ibm.com/docs/containers?topic=containers-storage_planning#non_persistent_overview

**Comment by lsteck** [comment]
OK, got it working by modifying the Dockerfile.  I'm going to document what I tried here.

First using original Docker file I add the following USER an RUN chgrp/chmod command before the existing RUN apt-get install maven command

```USER root
RUN chgrp -R 0 /usr/share && \
    chmod -R g+rwX /usr/share && \
    chgrp -R 0 /var/cache/apt && \
    chmod -R g+rwX /var/cache/apt
RUN apt-get update && apt-get install -y maven
```

Still getting the same Permissions denied error

`
 dpkg: error processing archive /var/cache/apt/archives/multiarch-support_2.27-3ubuntu1_amd64.deb (--unpack):
 error setting timestamps of '/usr/share/doc/multiarch-support/changelog.Debian.gz.dpkg-new': Permission denied
`

**Comment by lsteck** [comment]
Next I changed the base builder image from ibmjava:8-sdk to maven:3.6.3-jdk-8 and removed the apt-get install of Maven.

Here is the modified section of the Dockerfile
```
FROM maven:3.6.3-jdk-8 AS builder
LABEL maintainer="IBM Java Engineering at IBM Cloud"

WORKDIR /app

COPY pom.xml .
RUN mvn -N io.takari:maven:wrapper -Dmaven=3.5.0

```

**Comment by lsteck** [comment]
So next I removed the maven wrapper.  It is intended to make it easier for you to run a specific version of maven and since I now specify the version of Maven in the base image I don't think this is needed.  See: https://github.com/takari/maven-wrapper

So now docker file is as follows.
```
FROM maven:3.6.3-jdk-8 AS builder
LABEL maintainer="IBM Java Engineering at IBM Cloud"

WORKDIR /app

COPY pom.xml .

COPY . /app
RUN mvn install
```

**Comment by lsteck** [comment]
And I needed to update the /chart/base/values.yaml file to set the image:port value to be the port exposed by the Dockerfile/container.  Maybe we should document this?

**Comment by lsteck** [comment]
So the original Dockerfile builds just fine on IKS via Jenkins and Tekton.  The Jenkins pipeline runs perfectly.  The Tekton I'm getting a permissions error in the deploy stage deploy step

```
Initializing environment...
REGISTRY_URL: us.icr.io
REGISTRY_NAMESPACE: garage-dev-tools
IMAGE_NAME: java-spring-app-original
IMAGE_VERSION: 0.0.1-development.1
CHART_ROOT: ./chart
CHART: ./chart/base/Chart.yaml
CHART_NAME: base
Renaming chart from base to java-spring-app-original
cp: cannot create directory './chart/java-spring-app-original': Permission denied
```

**Comment by lsteck** [comment]
I added sudo in front of the cp command but that didn't fix it.
```
          # Update Chart name and version
          if [[ "${CHART_NAME}" != "${IMAGE_NAME}" ]]; then
            echo "Renaming chart from ${CHART_NAME} to ${IMAGE_NAME}"
            sudo cp -R "${CHART_ROOT}/${CHART_NAME}" "${CHART_ROOT}/${IMAGE_NAME}"
```
so as a work around I changed the name in Chart.yaml to match app `java-spring-app-original` to skip that command

**Comment by lsteck** [comment]
And changing name in Chart.yaml doesn't work because now I'm getting.

```
==> Skipping ./chart/java-spring-app-original
unable to check Chart.yaml file in chart: stat chart/java-spring-app-original/Chart.yaml: no such file or directory

```

**Comment by lsteck** [comment]
FWIW I'm unable to deploy [our java template](https://github.com/IBM/template-java-spring). I don't think this is related to our `igc enable` tasks so I think we can mark this as complete.
