### ISSUE TITLE
Cloud Native toolkit installation issue in IKS Cluster

### ISSUE THREAD

**Issue by MuthuSundaravadivel** [ibm-garage-cloud/planning#203]
**Describe the bug**
While installing CloudNative Developer toolkit in IKS Cluster. The following issues occurred.

Error: Error running command '.terraform/modules/dev_tools_jenkins_release/generic/tools/jenkins_release/scripts/deploy-jenkins.sh tools jenkins.gsi-dev-iks-cluster-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud 1.9.21 gsi-dev-iks-cluster-7ec5d722a0ab3f463fdc90eeb94dbc70-0000': exit status 1. Output: *** Fetching Jenkins helm chart from https://kubernetes-charts.storage.googleapis.com/
Error: unknown command "add" for "helm"
Run 'helm --help' for usage.

Error: timeout while waiting for state to become 'success' (timeout: 30s)

  on .terraform/modules/dev_serviceaccount_sonarqube/generic/cluster/serviceaccount/main.tf line 45, in resource "kubernetes_service_account" "create":
  45: resource "kubernetes_service_account" "create" { 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5441770/77559526-4e16c200-6ee2-11ea-9a53-c64f5b94b85a.png)

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ X] Jenkins
- [ ] Tekton
- [ X] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**

**Additional context**

**Comment by csantanapr** [comment]
What version of iks your trying to deploy?

**Comment by MuthuSundaravadivel** [comment]
version is 1.15.11_1533

**Comment by csantanapr** [comment]
@MuthuSundaravadivel 
What settings did you use?

creating new cluster or existing cluster
you ran the terraform twice on the same cluster without cleaning first, etc 

The more information you put here for use to reproduce, that would be helpful.

**Comment by csantanapr** [comment]
Can you try with  IKS 1.16 ?

**Comment by MuthuSundaravadivel** [comment]
Existing Cluster
![image](https://user-images.githubusercontent.com/5441770/77617908-421b1680-6f5b-11ea-8f4c-4842d66021b1.png)

**Comment by MuthuSundaravadivel** [comment]
@csantanapr  This my env details

# The type of cluster that will be created/used (kubernetes, openshift, ocp4, or crc) Use "openshift" for OpenShift 3.11
cluster_type="kubernetes"
# Flag indicating if we are using an existing cluster or creating a new one
cluster_exists="true"

# The prefix that should be applied to the cluster name and service names (if not provided
# explicitly). If not provided then the resource_group_name will be used as the prefix.
name_prefix="gsi-cloudnative-dev-squad"

# The cluster name can be provided (particularly if using an existing cluster). The value
# for cluster name used by the scripts will be set in the following order of presidence:
# - "${cluster_name}"
# - "${name_prefix}-cluster"
# - "${resource_group_name}-cluster"
cluster_name="gsi-dev-iks-cluster"

resource_group_name="gsi-cloudnative-dev-squad"
vlan_region="us-south"

# Flag indicating if we are using an existing postgres server or creating a new one
postgres_server_exists="false"

**Comment by MuthuSundaravadivel** [comment]
Even I have executed the terraform twice without cleaning. it's not working the same issue

**Comment by craig2898** [comment]
I tried this a couple of times. Both creating a new cluster as well as using an existing. Same error either way.

The last time used these settings:

# The type of cluster that will be created/used (kubernetes, openshift, ocp4, or crc) Use "openshift" for OpenShift 3.11
cluster_type="kubernetes"
# Flag indicating if we are using an existing cluster or creating a new one
cluster_exists="true"

# The prefix that should be applied to the cluster name and service names (if not provided
# explicitly). If not provided then the resource_group_name will be used as the prefix.
#name_prefix="<name prefix for cluster and services>"

# The cluster name can be provided (particularly if using an existing cluster). The value
# for cluster name used by the scripts will be set in the following order of presidence:
# - "${cluster_name}"
# - "${name_prefix}-cluster"
# - "${resource_group_name}-cluster"
cluster_name="garagetools-cluster"

resource_group_name="garagetools"
vlan_region="au-syd"

# Flag indicating if we are using an existing postgres server or creating a new one
postgres_server_exists="true"

IKS Info
![image](https://user-images.githubusercontent.com/25877134/77714506-4c0d4a00-702d-11ea-905f-59fa1886c258.png)

**Comment by csantanapr** [comment]
thanks for adding the settings used.
And good to know @craig2898 you tried iks 1.16 and no prefix

**Comment by MuthuSundaravadivel** [comment]
@csantanapr  Even I have tried "IKS 1.16"  the same issue occurred Could you please help me to resolve

**Comment by MuthuSundaravadivel** [comment]
@csantanapr  I have tried  IKS 1.17 still I am facing the same issue. Hereby I have attached all the details please help us to resolve the issue. 
ENV details:
<img width="894" alt="Screenshot 2020-03-27 at 3 08 47 PM" src="https://user-images.githubusercontent.com/5441770/77748848-09586b80-7047-11ea-8a44-7c54fd41d853.png">
IKS Cluster Details:
<img width="563" alt="Screenshot 2020-03-27 at 3 12 28 PM" src="https://user-images.githubusercontent.com/5441770/77748932-2f7e0b80-7047-11ea-9691-4b25800c6141.png">
Error Details:
<img width="1440" alt="Screenshot 2020-03-27 at 4 20 25 PM" src="https://user-images.githubusercontent.com/5441770/77749032-56d4d880-7047-11ea-8628-1854edbe2581.png">
<img width="1440" alt="Screenshot 2020-03-27 at 4 16 26 PM" src="https://user-images.githubusercontent.com/5441770/77749057-62280400-7047-11ea-8773-c7c639a42de1.png">

**Comment by csantanapr** [comment]
@craig2898 yours is also failing with helm add error?

@seansund Any clues what it could be the helm add issue?

**Comment by seansund** [comment]
could you run it again with these env variables set first:
```
export TF_LOG=DEBUG
export TF_LOG_PATH={some path}
```
When its done you can zip up the log, put it in box, and attach the link?

**Comment by csantanapr** [comment]
Just to inform I was able to reproduce using latest master from iteration zero, setup credentials, vlan on wdc06, to create new cluster iks

Problem with helm add
Problem with sonarqube
Problem with cloudant
```
module.dev_tools_sonarqube_release.null_resource.sonarqube_release (local-exec): >>> Retry count exceeded. https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about not available


Error: Error running command '.terraform/modules/dev_tools_jenkins_release/generic/tools/jenkins_release/scripts/deploy-jenkins.sh tools jenkins.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud 1.9.21 catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000': exit status 1. Output: *** Fetching Jenkins helm chart from https://kubernetes-charts.storage.googleapis.com/
Error: unknown command "add" for "helm"
Run 'helm --help' for usage.




Error: Error running command '.terraform/modules/dev_tools_sonarqube_release/generic/tools/sonarqube_release/scripts/deploy-sonarqube.sh tools sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud 4.4.0 sonarqube 2Gi "["https://binaries.sonarsource.com/Distribution/sonar-typescript-plugin/sonar-typescript-plugin-1.9.0.3766.jar","https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.14.0.18788.jar","https://github.com/checkstyle/sonar-checkstyle/releases/download/4.21/checkstyle-sonar-plugin-4.21.jar","https://binaries.sonarsource.com/Distribution/sonar-javascript-plugin/sonar-javascript-plugin-5.2.1.7778.jar","https://binaries.sonarsource.com/Distribution/sonar-python-plugin/sonar-python-plugin-1.14.1.3143.jar","https://binaries.sonarsource.com/Distribution/sonar-go-plugin/sonar-go-plugin-1.6.0.719.jar"]"': exit status 1. Output: *** Setting up kustomize directory
*** Updating patch-deployment.yaml with service account
*** Generating sonarqube yaml from helm template with plugins {https://binaries.sonarsource.com/Distribution/sonar-typescript-plugin/sonar-typescript-plugin-1.9.0.3766.jar,https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.14.0.18788.jar,https://github.com/checkstyle/sonar-checkstyle/releases/download/4.21/checkstyle-sonar-plugin-4.21.jar,https://binaries.sonarsource.com/Distribution/sonar-javascript-plugin/sonar-javascript-plugin-5.2.1.7778.jar,https://binaries.sonarsource.com/Distribution/sonar-python-plugin/sonar-python-plugin-1.14.1.3143.jar,https://binaries.sonarsource.com/Distribution/sonar-go-plugin/sonar-go-plugin-1.6.0.719.jar}
*** Building final kube yaml from kustomize into /home/devops/src/workspace/.tmp/sonarqube.yaml
*** Applying Sonarqube yaml to kube
configmap/sonarqube-sonarqube-config created
configmap/sonarqube-sonarqube-copy-plugins created
configmap/sonarqube-sonarqube-install-plugins created
secret/sonarqube-postgresql created
service/sonarqube-postgresql created
service/sonarqube-postgresql-headless created
service/sonarqube-sonarqube created
deployment.apps/sonarqube-sonarqube created
statefulset.apps/sonarqube-postgresql created
ingress.networking.k8s.io/sonarqube-sonarqube created
"toolkit-charts" has been added to your repositories
secret/sonarqube-access created
configmap/sonarqube-config created
*** Waiting for Sonarqube
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> Retry count exceeded. https://sonarqube.catalyst-demos-cluster-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud/about not available




Error: Error waiting for create resource instance (crn:v1:bluemix:public:cloudantnosqldb:us-east:a/98010327e775907f2d1bf637b10d2625:4a3d9bfd-8716-427b-b967-56f4a54e6576::) to be succeeded: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)

  on .terraform/modules/dev_infrastructure_cloudant/cloud-managed/services/cloudant/main.tf line 14, in resource "ibm_resource_instance" "cloudant_instance":
  14: resource "ibm_resource_instance" "cloudant_instance" {
```

**Comment by lsteck** [comment]
I'm seeing what helm add error also.
cluster_name="lds-test"
resource_group_name="catalyst-springboot"
vlan_region="us-south"

```
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> waiting for https://sonarqube.lds-test-793618-ddd93d3a0fef01f6b396b69d343df410-0000.us-south.containers.appdomain.cloud/about to be available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    43    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>>> Retry count exceeded. https://sonarqube.lds-test-793618-ddd93d3a0fef01f6b396b69d343df410-0000.us-south.containers.appdomain.cloud/about not available




Error: Error running command '.terraform/modules/dev_tools_jenkins_release/generic/tools/jenkins_release/scripts/deploy-jenkins.sh tools jenkins.lds-test-793618-ddd93d3a0fef01f6b396b69d343df410-0000.us-south.containers.appdomain.cloud 1.9.21 lds-test-793618-ddd93d3a0fef01f6b396b69d343df410-0000': exit status 1. Output: *** Fetching Jenkins helm chart from https://kubernetes-charts.storage.googleapis.com/
Error: unknown command "add" for "helm"
Run 'helm --help' for usage.




Error: Error waiting for create resource instance (crn:v1:bluemix:public:cloudantnosqldb:us-south:a/c6b82bced8251e389648625d5b3ed9bf:fe4fffef-3aeb-42a7-a8eb-848222d1e436::) to be succeeded: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)

  on .terraform/modules/dev_infrastructure_cloudant/cloud-managed/services/cloudant/main.tf line 14, in resource "ibm_resource_instance" "cloudant_instance":
  14: resource "ibm_resource_instance" "cloudant_instance" {

```

**Comment by csantanapr** [comment]
Here is a PR for jenkins helm add problem https://github.com/ibm-garage-cloud/garage-terraform-modules/pull/56

There is another problem with artifactory that @seansund is looking into it.

**Comment by MuthuSundaravadivel** [comment]
@csantanapr  I am not sure I have done changes correctly or not.  I have an updated version in my local machine "stage2-jenkins.tf" repo "ibm-garage-iteration-zero". Even though it's throwing the same error. To avoid the cloudant issue I have removed "stage3-cloudant.tf".   For your reference, I have attached the screenshot. 
<img width="841" alt="Screenshot 2020-03-28 at 2 23 35 PM" src="https://user-images.githubusercontent.com/5441770/77819449-ed190500-7100-11ea-80bd-65af1cdc7218.png">
<img width="1438" alt="Screenshot 2020-03-28 at 2 23 18 PM" src="https://user-images.githubusercontent.com/5441770/77819455-f6a26d00-7100-11ea-80b8-68dc872159c3.png">

I am requesting you to update the  "ibm-garage-iteration-zero" repo.
 Please correct me if I am missed anything.

**Comment by csantanapr** [comment]
There are 2 more PRs in progress that need to be resolved first. 

https://github.com/ibm-garage-cloud/garage-terraform-modules/pull/58

https://github.com/ibm-garage-cloud/garage-terraform-modules/pull/57

Then we will update iteration zero with the new references that include this 3 PRs

**Comment by csantanapr** [comment]
@lsteck @MuthuSundaravadivel @craig2898 

We believed we have fix all issues with IKS, latest commits in master https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/commits/master

Please fetch all commits from master, or git clone the whole repo.
Then try again creating a new cluster, or existing cluster that's doesn't have the toolkit partially installed

**Comment by MuthuSundaravadivel** [comment]
Cloud-Native toolkit installation successfully done in IKS 1.17. Thank you so much @csantanapr @seansund
