### ISSUE TITLE
`--no-git.requireCleanWorkingDir` : Issue

### ISSUE THREAD

**Issue by balasgit** [ibm-garage-cloud/planning#207]
**Describe the bug**
  `--no-git.requireCleanWorkingDir` 

Please stage and commit your changes.
Alternatively, use `--no-git.requireCleanWorkingDir` to include the changes in the release commit (or save `"git.requireCleanWorkingDir": false` in the configuration).
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**To Reproduce**
1. Install NodeJS Code Pattern and enable Pipeline which you will see the issues during build.

**Expected behavior**

**Screenshots**

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [X ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**

**Additional context**

Here is workaround which helped me to move forward
  “npm run clean --no-git-tag-version” on the package.json which solves and goes to next step in Jenkins

**Comment by seansund** [comment]
I'm not sure what `npm run clean --no-git-tag-version` is doing
