### ISSUE TITLE
Pact Verify Step : Pipeline Error - Inventory Services

### ISSUE THREAD

**Issue by balasgit** [ibm-garage-cloud/planning#210]
**Describe the bug**
 Pact Verify Step : Pipeline Error

**To Reproduce**
Deploy the Inventory App solution - Inventory Services. Followed the steps https://cloudnativetoolkit.dev/practical/inventory-part1/#deploy-the-inventory-app-solution (edited) 

**Expected behavior**
Pipeline working

**Screenshots**

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ X] Red Hat OpenShift Managed Services
- [ X] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [X ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**

**Additional context**
No `skipCheckstyle` flag. Applying build script. CODE Pattern: Spring Boot Microservice template. 
![image](https://user-images.githubusercontent.com/25986944/77666442-f7939d00-6f4e-11ea-86bd-38ba705e422c.png)

---
# Source: inventory-management-svc-balasaustin/templates/route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: inventory-management-svc-balasaustin
spec:
  to:
    kind: Service
    name: inventory-management-svc-balasaustin
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
---
# Source: inventory-management-svc-balasaustin/templates/ingress.yaml

Deploying into: gsi-learning-ocp311-cluster/dev-bala-austin.
service/inventory-management-svc-balasaustin unchanged
deployment.apps/inventory-management-svc-balasaustin configured
route.route.openshift.io/inventory-management-svc-balasaustin unchanged
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Health Check)
[Pipeline] sh
Logging into IBM Cloud - eu-gb/gsi-cloudnative-squad/gsi-learning-ocp311-cluster
Logging into IBM Cloud - openshift
Initializing environment...
Successfully reached health endpoint: https://inventory-management-svc-balasaustin-dev-bala-austin.gsi-learning-ocp311-clu-7ec5d722a0ab3f463fdc90eeb94dbc70-0001.eu-gb.containers.appdomain.cloud/health
=====================================================================
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Pact verify)
[Pipeline] sh
+ . ./env-config
++ IMAGE_VERSION=0.0.2
++ IMAGE_NAME=inventory-management-svc-balasaustin
++ HOST=inventory-management-svc-balasaustin-dev-bala-austin.gsi-learning-ocp311-clu-7ec5d722a0ab3f463fdc90eeb94dbc70-0001.eu-gb.containers.appdomain.cloud
++ PROTOCOL=https
++ PORT=443
+ ./gradlew pactVerify -PpactBrokerUrl= -PpactProtocol=https -PpactHost=inventory-management-svc-balasaustin-dev-bala-austin.gsi-learning-ocp311-clu-7ec5d722a0ab3f463fdc90eeb94dbc70-0001.eu-gb.containers.appdomain.cloud -PpactPort=443 -Ppact.verifier.publishResults=true

> Configure project :
No `skipCheckstyle` flag. Applying build script

FAILURE: Build failed with an exception.

* Where:
Script '/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-svc-balasaustin/gradle/build-pact-provider.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by seansund** [comment]
The solution repository has been updated. Please create a new project from the template and try again
