### ISSUE TITLE
Verify Pact Step Error: Inventory BFF app

### ISSUE THREAD

**Issue by balasgit** [ibm-garage-cloud/planning#214]
**Describe the bug**
 Verify Pact Error

**To Reproduce**
  Deplou Inventory App BFF - https://cloudnativetoolkit.dev/practical/inventory-part1

**Expected behavior**
 Pipeline success

**Screenshots**
![image](https://user-images.githubusercontent.com/25986944/77778468-03e72b00-701f-11ea-87d5-bb89068c4f57.png)

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ X] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  MACOS
 - Browser [e.g. chrome, safari] Firefox 62

**Additional context**
Failures:

  1) Verifying a pact between inventory-management-bff and inventory-management-svc Given base state a request for stock items with GET /stock-items returns a response which has status code 200
     Failure/Error: expect(response_status).to eql expected_response_status

       expected: 200
            got: 502

       (compared using eql?)

  2) Verifying a pact between inventory-management-bff and inventory-management-svc Given base state a request for stock items with GET /stock-items returns a response which has a matching body
     Failure/Error: expect(response_body).to match_term expected_response_body, diff_options, example

       Actual: <!DOCTYPE html>
       <html lang="en">
       <head>
       <meta charset="utf-8">
       <title>Error</title>
       </head>
       <body>
       <pre>BadGateway: There was an error<br> &nbsp; &nbsp;at new HttpError (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/node_modules/typescript-rest/src/server/model/errors.ts:11:9)<br> &nbsp; &nbsp;at new BadGateway (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/src/controllers/stock-items.controller.ts:11:5)<br> &nbsp; &nbsp;at StockItemsController.&lt;anonymous&gt; (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/src/controllers/stock-items.controller.ts:36:13)<br> &nbsp; &nbsp;at Generator.throw (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at rejected (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/node_modules/tslib/tslib.js:108:69)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre>
       </body>
       </html>

       Diff
       --------------------------------------
       Key: [31m-[0m[31m is expected 
       [0m[32m     +[0m[32m is actual 
       [0mMatching keys and values are not shown

       [0m[31m-[
       [0m[31m-  {
       [0m[31m-    "id": "1234",
       [0m[31m-    "manufacturer": "My manufacturer",
       [0m[31m-    "name": "product name",
       [0m[31m-    "price": 20,
       [0m[31m-    "stock": 1000
       [0m[31m-  },
       [0m[31m-]
       [0m[32m+<!DOCTYPE html>
       [0m[32m+<html lang="en">
       [0m[32m+<head>
       [0m[32m+<meta charset="utf-8">
       [0m[32m+<title>Error</title>
       [0m[32m+</head>
       [0m[32m+<body>
       [0m[32m+<pre>BadGateway: There was an error<br> &nbsp; &nbsp;at new HttpError (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/node_modules/typescript-rest/src/server/model/errors.ts:11:9)<br> &nbsp; &nbsp;at new BadGateway (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/src/controllers/stock-items.controller.ts:11:5)<br> &nbsp; &nbsp;at StockItemsController.&lt;anonymous&gt; (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/src/controllers/stock-items.controller.ts:36:13)<br> &nbsp; &nbsp;at Generator.throw (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at rejected (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/node_modules/tslib/tslib.js:108:69)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre>
       [0m[32m+</body>
       [0m[32m+</html>
       [0m

       Description of differences
       --------------------------------------
       * Expected an Array (like [{"id"=>"1234", "manufacturer"=>"My manufacturer", "name"=>"product name", "price"=>20, "stock"=>1000}]) but got a String ("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>BadGateway: There was an error<br> &nbsp; &nbsp;at new HttpError (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/node_modules/typescript-rest/src/server/model/errors.ts:11:9)<br> &nbsp; &nbsp;at new BadGateway (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/src/controllers/stock-items.controller.ts:11:5)<br> &nbsp; &nbsp;at StockItemsController.&lt;anonymous&gt; (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/src/controllers/stock-items.controller.ts:36:13)<br> &nbsp; &nbsp;at Generator.throw (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at rejected (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/node_modules/tslib/tslib.js:108:69)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre>\n</body>\n</html>\n") at $

  3) Verifying a pact between inventory-management-bff and inventory-management-svc Given base state a request for stock items with GET /stock-items returns a response which includes headers "Content-Type" which equals "application/json"
     Failure/Error: expect(header_value).to match_header(name, expected_header_value)
       Expected header "Content-Type" to equal "application/json", but was "text/html; charset=utf-8"

1 interaction, 1 failure

Failed interactions:

* A request for stock items given base state

WARN: Cannot publish verification for inventory-management-bff as there is no link named pb:publish-verification-results in the pact JSON. If you are using a pact broker, please upgrade to version 2.0.0 or later.

    at ChildProcess.<anonymous> (/home/jenkins/agent/workspace/dev-bala-austin/dev-bala-austin-gsi-enablement-one.inventory-management-bff-balasaustin/node_modules/@pact-foundation/pact-node/src/verifier.ts:156:55)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:323:22)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by seansund** [comment]
The solution has been updated. Please create a new repo from the template and test again.
