### ISSUE TITLE
Slightly confusing flow with new CLI changes 

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#221]
**Describe the bug**

When you perform the flow to register a new tekton pipeline with the new CLI, it says you namespace is not created, and gives you a sample command to run. When you run this and then run the same pipeline command it then says you need to add `--tekton` if you have already asked for tekton the prompted command should include the `--tekton` on  it so the tasks and pipelines are displayed.

First Command
```
igc pipeline -n dev-mjp --tekton
The target namespace does not exist
Create the namespace by running: igc namespace dev-mjp
```

Second

```
Creating Image PipelineResource
No Pipelines found in dev-mjp namespace. Skipping PipelineRun creation
Install Tekton tasks and pipelines into your namespace by running: igc namespace dev-mjp --tekton
```

**Expected behavior**
Make the first prompt match your goal which is adding tekton tasks and pipelines to my project namespace

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [X] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by seansund** [comment]
What version of the CLI do you have? `igc --version`

**Comment by mjperrins** [comment]
I am running `0.4.9-beta.32` we can check this next week

**Comment by seansund** [comment]
Please retest. Changes pushed with this story ibm-garage-cloud/planning#195

**Comment by seansund** [comment]
@mjperrins Is this still an issue or have recent updates to the CLI and the documentation addressed this?
