### ISSUE TITLE
Update cluster_type to distinguish plain ocp versus roks

### ISSUE THREAD

**Issue by rbarcia** [ibm-garage-cloud/planning#222]
Current configuration, openshift, ocp3, ocp4 assumes IBM Cloud
cluster_type — Specify the existing cluster’s type
kubernetes — Kubernetes
   openshift — OpenShift v3. //today means ROKS
   ocp3 — OpenShift v3. //today means ROKS
   ocp4 — OpenShift v4. // Today means ROKS
    crc — CodeReady Containers

Changes:  

cluster_type — Specify the existing cluster’s type
  kubernetes — OpenSource Kubernetes, minikub
  icks = IBM Cloud Kubernetes Service
  crc — CodeReady Containers. //dev config for OpenShift stack
  roks4 = managed IBM OpenShift v4 + managed IBM Services
  ocp3 — OpenShift v3.   // Provisions OCP only config with OCP efk, monitoring, etc...  No IBM Cloud services
  ocp4 — OpenShift v4.  // Provisions OCP only config with OCP efk, monitoring, etc...  No IBM Cloud services

**Comment by rbarcia** [comment]
Talking more with Sean, we are thinking of getting a bit more explicit selecting perhaps the managed services i want to use.

**Comment by seansund** [comment]
How about this for values?

cloud_manager: ibm | crc | self-managed | aws | azure | ...
cluster_type: kubernetes | openshift | ocp
cluster_version: 3.11 | 4.2 | 4.3

- `crc` is really just a special case of `self-managed` but we could call it out as a low-resource dev environment
- If you aren't going to be using any cloud-specific services then `self-managed` and `aws`, `azure` are basically the same

**Comment by seansund** [comment]
Selections:
Logging stack
Monitoring stack
Metering stack
