### ISSUE TITLE
Chore: Update tekton tasks with latest logic from Jenkins steps

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#23]
The Jenkins steps have been updated to support a cleaner flow for the pipeline. Those changes need to be synchronized with the Tekton tasks

Pipeline source - https://github.com/ibm-garage-cloud/garage-pipelines/tree/master/stable
Tekton tasks - https://github.com/ibm-garage-cloud/ibm-garage-tekton-tasks

**Comment by csantanapr** [comment]
found a difference this week to correct REGISTRY_NAMESPACE should be extracted from img url
in all steps of helm package task

We are using the new git repo https://github.com/IBM/ibm-garage-tekton-tasks
