### ISSUE TITLE
Pipeline Task Error Health TASK - Code Pattern React

### ISSUE THREAD

**Issue by balasgit** [ibm-garage-cloud/planning#239]
**Describe the bug**
Pipeline Tekton Task is failing on the HEalth step while trying to deploy the REach App on OCP 4.3

**To Reproduce**
Get Template https://github.com/IBM/template-node-react/generate
Clone Repo
Make changes as per Readme
Deploy the Pipeline via Tekton 
Health task is getting stuck and throws error

**Expected behavior**
Pipeline should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/25986944/77957441-18365c80-7299-11ea-9c28-108664e8a69e.png)
![image](https://user-images.githubusercontent.com/25986944/77957492-2f754a00-7299-11ea-9765-a9d5e1fa73d1.png)
![image](https://user-images.githubusercontent.com/25986944/77957619-5d5a8e80-7299-11ea-9f3c-f91859b0a446.png)
![image](https://user-images.githubusercontent.com/25986944/77957728-88dd7900-7299-11ea-8a16-80f286a96bf4.png)
![image](https://user-images.githubusercontent.com/25986944/77957735-8c710000-7299-11ea-8ecb-df213d811a6b.png)

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ X] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ X] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  MAC OS
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 62

**Additional context**
step-git-source-ocp4-aus-cp1-git-tdvxv
{"level":"info","ts":1585592493.3096588,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"info","ts":1585592495.3327348,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"info","ts":1585592497.3355334,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/gsi-enablement-one/ocp4-aus-cp1.git @ master in path /workspace/source"}
{"level":"info","ts":1585592497.4286554,"logger":"fallback-logger","caller":"git/git.go:130","msg":"Successfully initialized and updated submodules in path /workspace/source"}

step-health-check
{"level":"info","ts":1585592493.7069776,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
Initializing environment...
Could not reach health endpoint: https://ocp4-aus-cp1-dev-aus-cp.gsi-learning-ocp43-clus-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.eu-gb.containers.appdomain.cloud/health

**Comment by balasgit** [comment]
I dont have options to edit issues so adding screenshot which may be give clue why Health task failing 

![image](https://user-images.githubusercontent.com/25986944/77958786-2dac8600-729b-11ea-8c8d-318ed9851fc4.png)

![image](https://user-images.githubusercontent.com/25986944/77958792-31400d00-729b-11ea-9a7a-c69e959418ef.png)

**Comment by seansund** [comment]
A couple of questions:

- Which namespace are you running in?
- Did you use `igc namespace` to create it?
- Can you post the yaml from your deployment object?
- Can you run the following for the service account your deployment/pod is running as - `kubectl get serviceaccount {service account name} -n {namespace} -o yaml`

**Comment by balasgit** [comment]
**For #1 & #2, here is screenshot**
![image](https://user-images.githubusercontent.com/25986944/78063324-a243fb00-7355-11ea-8395-795307c8b8af.png)

**Note:**  Pls clarify if the IGC namespace cmd will also create project in OCP.. If so, I can avoid & tell Matt also not to run the command.. 

**Here is the YAML for #3**
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ocp4-aus-cp1","app.kubernetes.io/instance":"ocp4-aus-cp1","app.kubernetes.io/name":"ocp4-aus-cp1","helm.sh/chart":"ocp4-aus-cp1-0.0.4"},"name":"ocp4-aus-cp1","namespace":"dev-codepatterns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"ocp4-aus-cp1","app.kubernetes.io/name":"ocp4-aus-cp1"}},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"ocp4-aus-cp1","app.kubernetes.io/name":"ocp4-aus-cp1"}},"spec":{"containers":[{"env":[{"name":"INGRESS_HOST","value":"ocp4-aus-cp1-dev-codepatterns.gsi-learning-ocp43-clus-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.eu-gb.containers.appdomain.cloud"},{"name":"PROTOCOLS","value":"http,https"},{"name":"LOG_LEVEL","value":"debug"}],"image":"uk.icr.io/gsi-cloudnative-squad/ocp4-aus-cp1:0.0.4","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/","port":"http"}},"name":"ocp4-aus-cp1","ports":[{"containerPort":3000,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/","port":"http"}},"resources":null}]}}}}
  selfLink: /apis/apps/v1/namespaces/dev-codepatterns/deployments/ocp4-aus-cp1
  resourceVersion: '3732419'
  name: ocp4-aus-cp1
  uid: 9e3d27ac-e40e-4f76-b625-f26647e078db
  creationTimestamp: '2020-03-31T17:02:53Z'
  generation: 1
  namespace: dev-codepatterns
  labels:
    app: ocp4-aus-cp1
    app.kubernetes.io/instance: ocp4-aus-cp1
    app.kubernetes.io/name: ocp4-aus-cp1
    helm.sh/chart: ocp4-aus-cp1-0.0.4
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ocp4-aus-cp1
      app.kubernetes.io/name: ocp4-aus-cp1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ocp4-aus-cp1
        app.kubernetes.io/name: ocp4-aus-cp1
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: ocp4-aus-cp1
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: INGRESS_HOST
              value: >-
                ocp4-aus-cp1-dev-codepatterns.gsi-learning-ocp43-clus-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.eu-gb.containers.appdomain.cloud
            - name: PROTOCOLS
              value: 'http,https'
            - name: LOG_LEVEL
              value: debug
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'uk.icr.io/gsi-cloudnative-squad/ocp4-aus-cp1:0.0.4'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2020-03-31T17:02:54Z'
      lastTransitionTime: '2020-03-31T17:02:54Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2020-03-31T17:12:54Z'
      lastTransitionTime: '2020-03-31T17:12:54Z'
      reason: ProgressDeadlineExceeded
      message: ReplicaSet "ocp4-aus-cp1-5bfbd74f69" has timed out progressing.

**Here is #4** 

 kubectl get serviceaccount
NAME       SECRETS   AGE
builder    2         123m
default    2         123m
deployer   2         123m
pipeline   3         123m

kubectl get serviceaccount default -o yaml
apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-s6p74
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-03-31T16:43:07Z"
  name: default
  namespace: dev-codepatterns
  resourceVersion: "3713577"
  selfLink: /api/v1/namespaces/dev-codepatterns/serviceaccounts/default
  uid: 8ba47fa8-f9fa-41f4-af2a-c2e59dcb2bd1
secrets:
- name: default-token-dfh99
- name: default-dockercfg-s6p74
balas-mbp:ibm-garage-developer-guide bala$

**Comment by balasgit** [comment]
[deploy.log](https://github.com/ibm-garage-cloud/planning/files/4411063/deploy.log)
[build.log](https://github.com/ibm-garage-cloud/planning/files/4411064/build.log)
[test(1).log](https://github.com/ibm-garage-cloud/planning/files/4411065/test.1.log)
[health.log](https://github.com/ibm-garage-cloud/planning/files/4411066/health.log)

**Comment by balasgit** [comment]
Toolkit version which am running in 4.10 and another team member who runs 4.0 beta-32. 

We are seeing 2 different behaviour for the same code pattern as it throws error on 4.10 and works on 4.0.9 beta. Just findings if this helps.

**Comment by seansund** [comment]
Your underlying issue is that the pull secrets have not been set up in your namespace for your `default` service account which should have been done with the `igc namespace` command. Can you run:

```
kubectl get secrets -n dev-codepatterns
kubectl get serviceaccount/default -n dev-codepatterns -o yaml
```

**Comment by seansund** [comment]
Also, which cluster is this?

**Comment by balasgit** [comment]
Cluster: gsi-learning-ocp43-cluster 

**kubectl get secrets -n dev-codepatterns**
NAME                              TYPE                                  DATA   AGE
argocd-access                     Opaque                                2      174m
artifactory-access                Opaque                                5      174m
builder-dockercfg-n2tfl           kubernetes.io/dockercfg               1      175m
builder-token-4mhgn               kubernetes.io/service-account-token   4      175m
builder-token-8vzfx               kubernetes.io/service-account-token   4      175m
default-dockercfg-s6p74           kubernetes.io/dockercfg               1      175m
default-token-dfh99               kubernetes.io/service-account-token   4      175m
default-token-dsptg               kubernetes.io/service-account-token   4      175m
deployer-dockercfg-cfcv6          kubernetes.io/dockercfg               1      175m
deployer-token-kscxz              kubernetes.io/service-account-token   4      175m
deployer-token-qlnfv              kubernetes.io/service-account-token   4      175m
gsi-enablement-one-ocp4-aus-cp1   kubernetes.io/basic-auth              7      171m
ibmcloud-apikey                   Opaque                                2      174m
pipeline-dockercfg-d26zv          kubernetes.io/dockercfg               1      175m
pipeline-token-6kjdg              kubernetes.io/service-account-token   4      175m
pipeline-token-nd9vf              kubernetes.io/service-account-token   4      175m
sonarqube-access                  Opaque                                2      174m

balas-mbp:ibm-garage-developer-guide bala$ **kubectl get serviceaccount/default -n dev-codepatterns -o yaml**
apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-s6p74
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-03-31T16:43:07Z"
  name: default
  namespace: dev-codepatterns
  resourceVersion: "3713577"
  selfLink: /api/v1/namespaces/dev-codepatterns/serviceaccounts/default
  uid: 8ba47fa8-f9fa-41f4-af2a-c2e59dcb2bd1
secrets:
- name: default-token-dfh99
- name: default-dockercfg-s6p74

**Comment by balasgit** [comment]
POD Logs

oc describe pod ocp4-aus-cp1-5bfbd74f69-lxmdx
Name:               ocp4-aus-cp1-5bfbd74f69-lxmdx
Namespace:          dev-codepatterns
Priority:           0
PriorityClassName:  <none>
Node:               10.113.191.150/10.113.191.150
Start Time:         Tue, 31 Mar 2020 12:02:54 -0500
Labels:             app.kubernetes.io/instance=ocp4-aus-cp1
                    app.kubernetes.io/name=ocp4-aus-cp1
                    pod-template-hash=5bfbd74f69
Annotations:        cni.projectcalico.org/podIP=172.30.68.126/32
                    cni.projectcalico.org/podIPs=172.30.68.126/32
                    k8s.v1.cni.cncf.io/networks-status=[{
    "name": "k8s-pod-network",
    "ips": [
        "172.30.68.126"
    ],
    "dns": {}
}]
                openshift.io/scc=restricted
Status:         Pending
IP:             172.30.68.126
Controlled By:  ReplicaSet/ocp4-aus-cp1-5bfbd74f69
Containers:
  ocp4-aus-cp1:
    Container ID:   
    Image:          uk.icr.io/gsi-cloudnative-squad/ocp4-aus-cp1:0.0.4
    Image ID:       
    Port:           3000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      INGRESS_HOST:  ocp4-aus-cp1-dev-codepatterns.gsi-learning-ocp43-clus-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.eu-gb.containers.appdomain.cloud
      PROTOCOLS:     http,https
      LOG_LEVEL:     debug
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dfh99 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-dfh99:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dfh99
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                     Message
  ----     ------     ----                ----                     -------
  Normal   Scheduled  <unknown>           default-scheduler        Successfully assigned dev-codepatterns/ocp4-aus-cp1-5bfbd74f69-lxmdx to 10.113.191.150
  Normal   Pulling    2h (x4 over 2h)     kubelet, 10.113.191.150  Pulling image "uk.icr.io/gsi-cloudnative-squad/ocp4-aus-cp1:0.0.4"
  Warning  Failed     2h (x4 over 2h)     kubelet, 10.113.191.150  Failed to pull image "uk.icr.io/gsi-cloudnative-squad/ocp4-aus-cp1:0.0.4": rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password: unauthorized: authentication required
  Warning  Failed     2h (x4 over 2h)     kubelet, 10.113.191.150  Error: ErrImagePull
  Warning  Failed     19m (x706 over 2h)  kubelet, 10.113.191.150  Error: ImagePullBackOff
  Normal   BackOff    4m (x772 over 2h)   kubelet, 10.113.191.150  Back-off pulling image "uk.icr.io/gsi-cloudnative-squad/ocp4-aus-cp1:0.0.4"

**Comment by seansund** [comment]
Please try the following:

```
npm i -g @ibmgaragecloud/cloud-native-toolkit-cli
igc namespace dev-codepatterns
```

Verify the environment by running:

```
kubectl get secrets -n dev-codepatterns
kubectl get serviceaccount/default -n dev-codepatterns -o yaml
```

- The first command should list several secrets with name like `.*icr-io`
- The second command should include those `.*icr-io` secrets under the `imagePullSecrets` of the serviceAccount

You should also see that those issues in your pods should resolve themselves eventually (you can delete the pod to force the cluster to recreate it if you don't want to wait for the pod to resolve itself).

Now you can rerun your pipeline and the health check should work.

**Comment by balasgit** [comment]
Health Step is passed but it failed in Gitops step

![image](https://user-images.githubusercontent.com/25986944/78075676-96aeff00-736a-11ea-8212-aad90111c9d6.png)


{"level":"info","ts":1585689146.3013644,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
Initializing environment...
'username' not set. Not triggering CD pipeline

**Comment by balasgit** [comment]
Found out we need to setup setup of the ArgoCD git ops first before the pipeline can trigger it

**Comment by balasgit** [comment]
[gitops.log](https://github.com/ibm-garage-cloud/planning/files/4411644/gitops.log)

**Comment by seansund** [comment]
Looks like this issue is resolved now, right?

**Comment by balasgit** [comment]
Yes..

**Comment by balasgit** [comment]
discussing with Matt on this.. Even though git ops is not configured, still pipeline shouldnt fail. Can you let me know or should i open new defect ?

**Comment by seansund** [comment]
I agree that it shouldn't fail. Could you create a different ticket for that?
