### ISSUE TITLE
ICPA 4.1 fails to install on OCP 4.3 Toolkit

### ISSUE THREAD

**Issue by ogaye-ibm** [ibm-garage-cloud/planning#251]
**Describe the bug**
ICPA 4.1 fails to install on OCP 4.3 Toolkit

**To Reproduce**
1. Install latest toolkit (release  1.2.1?) on a 4.31 OCP cluster on IBM Cloud , Tekton works fine
2. Install from CLI ICPA 4.1 
3. See error
Tekton is partially broken. When you un-install ICPA, Tekton is all gone
The knativeserving.operator.knative.dev resource is not ready. There might a problem that is preventing the knativeserving.operator.knative.dev resource from becoming ready, or additional time might be required to get ready.
Run the following commands to examine the status of the knativeserving.operator.knative.dev resource:
oc -n "knative-serving" describe "knativeserving.operator.knative.dev" "knative-serving"
Once the problem is resolved or the resource becomes ready, re-run the installer to complete the installation process.
knativeserving-controller  Failed to update status for KnativeServing "knative-serving": Operation cannot be fulfilled on knativeservings.operator.knative.dev "knative-serving": the object has been modified; please apply your changes to the latest version and try again

**Expected behavior**
Toolkit still working, ICPA installs and works

**Screenshots**

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**

**Additional context**

**Comment by ogaye-ibm** [comment]
@seansund @mjperrins fyi

**Comment by seansund** [comment]
This is not a but with the Toolkit but a bug with ICP4A. Have you created a ticket against them?
