### ISSUE TITLE
igc credentials fails on a OCP3 cluster

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#252]
**Describe the bug**
When I ran `igc credentials` on garage-dev-ocp3-cluster, I got the error: `Error getting credentials: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null`. Larry got the same error using the same cluster. IKS and OCP4 clusters worked correctly.

**To Reproduce**
1. oc login (log in to garage-dev-ocp3-cluster (or another OCP3 cluster?))
2. oc get pods -n tools (confirm I'm logged in)
3. igc credentials
`Error getting credentials: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null`
4. igc credentials -n tools
`Error getting credentials: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null`
5. igc endpoints -n tools (lists 5 URLs: swaggereditor-dashboard, argocd-server, etc.)
6. igc dashboard (works, opens dashboard populated with 7 panels)

**Expected behavior**
igc credentials should return a Credentials JSON doc.

**Screenshots**
None

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS v10.15.3
 - Browser [e.g. chrome, safari] Google Chrome v80.0.3987.132

**Additional context**

**Comment by lsteck** [comment]
Yes, I'm seeing the same thing.

With garage-dev-iks-cluster
after command
ic ks cluster config --cluster garage-dev-iks-cluster
igc credentials commands works

With garage-dev-ocp4-cluster 
ic ks cluster config --cluster garage-dev-ocp4-cluster
after logging in with command
oc login --token=<my-token> --server=https://c100-e.us-east.containers.cloud.ibm.com:30238
igc credentials command works.

But with garage-dev-ocp3-cluster
ic ks cluster config --cluster garage-dev-ocp3-cluster
after logging in with command
oc login https://c100-e.us-east.containers.cloud.ibm.com:32724 --token=<my-token>
igc credentials returns the error:
Error getting credentials: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null

**Comment by seansund** [comment]
What version of the cli are you using?

**Comment by lsteck** [comment]
> igc --version
0.4.14

**Comment by seansund** [comment]
I found the problem. On OCP3 the jenkins-access secret has not been created and the logic didn't handle that properly
