### ISSUE TITLE
ArgoCD: ingress resources out of sync for hours

### ISSUE THREAD

**Issue by davesteinberg** [ibm-garage-cloud/planning#3]
**Describe the bug**

In doing the MOOC homework (team four), I'm seeing a problem with Argo CD: In each application I've created, the ingress resource remains out of sync for hours before finally becoming healthy.

I can see with `oc get` that Argo is correctly creating the ingress resource, and I can use `igc ingress` to open the path in browser and verify that it is working. But Argo remains unconvinced. When I look at the diff on the ingress in the Argo UI, it shows a blank left side.

Finally, after several hours pass, the application becomes healthy. However, I see no events listed, so I have no idea what happened.

**To Reproduce**

1. Go to http://argocd.mooc-four-rhos-cluster.sjc04.containers.appdomain.cloud/
2. Create an application as per the [MOOC instructions](https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/practical/inventory-part2/#using-cd-to-deliver-to-test).
3. Observe that all resources go healthy except the ingress, which remains out of sync.
4. Return from time to time to check on the status of the application. After several hours, mine finally went healthy. 

**Expected behavior**

The full application should become healthy, as soon as the resources have all been applied.

**IBM Cloud**

- [ ] IBM Kubernetes Service Managed Service
- [X] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [X] Argo CD
- [ ] IBM Image Registry

**Additional context**

Discussion here: https://ibm-garage.slack.com/archives/CQ2FYU9RN/p1574460794137600

**Comment by mjperrins** [comment]
I believe you Argo came back into Sync, we did have to manually patch your server, happy for you to try adn the same steps on `mooc-team-one` so we can work out the issue on the patch, the iZero content has already been updated, so no setups and installs will not be effected, it was related to a Redis requirement that came in just before MOOC kicked off

**Comment by jmereaux** [comment]
My out of sync warnings are now gone on the team two instance. Was the patch applied here also?

**Comment by davesteinberg** [comment]
Sweet! I just tried deleting my application in Argo CD, and recreating it (of course, I verified that all the resources had been deleted before I recreated it). Argo showed the ingress resource as healthy immediately. A few moments later, the deployment completed, and the whole application is looking good now.

@mjperrins I'd say that your manual patching did the trick. Will new Iteration Zero deployments have this problem, or should it be fully resolved now?

**Comment by mjperrins** [comment]
The issue has been fixed in iteration zero , so no new installations will have an issue

**Comment by osowski** [comment]
@mjperrins For future reference and other deployments of ArgoCD, can you detail what the manual patching that was performed?  I see this issue on numerous ArgoCD on OCP while using Ingress objects and it would be nice to know if this is something universal.
