### ISSUE TITLE
Update process for handling the container registry

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#311]
The current process makes a lot of assumptions when the cluster is provisioned and would be more flexible if some of the steps were moved elsewhere. One of the major assumptions in both the terraform and CLI is that the IBM Cloud container registry will be used. Another is that the CR namespace should match the resource group.

## Current process

**Terraform**

- IBM Cloud module creates the CR namespace based on the resource group (at this point it can fail silently if the namespace was created by another account #333 )
- IBM Cloud module sets up the pull secrets for the IBM CR
- IBM Cloud module creates the `ibmcloud-config` ConfigMap with the registry host as the IBM Cloud CR host name and the registry namespace as the resource group and stores the credentials in the 
- Namespace module copies the pull secrets into the namespaces as it creates them (currently only needed for `tools` namespace on IKS until #266 is addressed; also related to #179)

**CLI**

- CLI `sync` command _always_ copies the pull secrets into the new namespace

## Proposed changes

**Design**

- The `ibmcloud-config` ConfigMap shouldn't contain the registry information
- A separate `imageregistry-config` and `imageregistry-access` ConfigMap and Secret should store the image registry information

**Terraform**

- Terraform IBM Cloud module shouldn't do anything to create the CR namespace or set up the pull secrets
- The Namespace module shouldn't copy pull secrets

**CLI**

`sync` command should check if the image registry url is the IBM Cloud CR

 1. if it is and the pull secret exists in the default namespace, copy the pull secrets
 2. if it is and the pull secret does not exist in the default namespace, stop and give a message to create the pull secrets with `ibmcloud cr pull-secret apply` (or run the command for them
 3. if the value is set but it isn't the IBM Cloud CR then do nothing
 4. if the value isn't set then prompt the user to set it (and optionally have the CLI create the namespace)

**Comment by seansund** [comment]
@perrins @mjperrins @csantanapr

**Comment by csantanapr** [comment]
Yes I had problems when I was using OCP4 and just wanted to use the internal registry of OpenShift 

I really like this change to clean things and make it easier

**Comment by perrins** [comment]
I agree more iteration and improvement from our original design , look forward to the code changes , some of this is the real magic of what has been don't with izero setting up the secrets and configmaps consistently for use by pipeline technologies

**Comment by seansund** [comment]
Not sure why this wasn't considered before but the IBM Container Registry setup will be moved into a separate module. For now, that module will be included by default for the IBM Cloud install. We will also create a k8s version of the registry to configure other container registries within the cluster.

The same will be done for the Git configuration as well...
