### ISSUE TITLE
Add tekton Github and Gitlab Web hook triggers

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#323]
@csantanapr commented on [Mon Mar 09 2020](https://github.com/ibm-garage-cloud/ibm-garage-tekton-tasks/issues/13)

Add tekton Github and Gitlab Web hook triggers

This will allow developer when setting the pipeline to configure git repo with a webhook, then pushing code to the repo will trigger the pipeline.

The `igc` command line then can automate this one time configuration setup with `igc pipeline --tekton`

---

@csantanapr commented on [Mon Mar 09 2020](https://github.com/ibm-garage-cloud/ibm-garage-tekton-tasks/issues/13#issuecomment-596520081)

This is possible now that the OpenShift Pipelines Operator v0.10.7 installs tekton controller v0.10.1 and triggers v0.2.1

```
oc describe pod tekton-pipelines-controller-cbbbb9b6-cnzbk -n openshift-pipelines | grep Image
    Image:         quay.io/openshift-pipeline/tektoncd-pipeline-controller:v0.10.1
```
```
oc describe pod tekton-triggers-controller-84766fbf76-zpggx -n openshift-pipelines | grep Image
    Image:         quay.io/openshift-pipeline/tektoncd-triggers-controller:v0.2.1
```

**Comment by seansund** [comment]
@holly-cummins has some example content to share

**Comment by rampadc** [comment]
A workaround to generate triggertemplate, triggerbinding and event listener until `igc pipeline --tekton` adds triggers by default https://github.com/rampadc/cntk-tekton-trigger

**Comment by rampadc** [comment]
Hey @seansund, is there a difference between this issue and #283?
