### ISSUE TITLE
Manager role on Kubernetes Service grants RBAC cluster-admin cluster role

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#332]
`terraform/scripts/acp-user.sh` grants the Manager role to All Services, which enables users to configure the service instance, such as adding and removing databases in a database service. The script grants the Writer role to Kubernetes Service, but the service "inherits" the Manager role from the broader All Services category. (This inheritance behavior caused the problem in #327 where users could delete worker nodes.)

[Manager role on Kubernetes Service](https://cloud.ibm.com/docs/containers?topic=containers-access_reference#service) makes the user a cluster-admin in the clusters, including these abilities:
> - Read/write access to all resources in every namespace
> - Create RBAC roles and role bindings in a namespace or cluster roles and cluster role bindings in all namespaces

This is access we want the environment admins to have (as configured by `terraform/scripts/acp-admin.sh`), but broader than we want users to have.

The IAM framework does not make it easy to define this Manager configuration access broadly for all service instances except IKS clusters.

**Comment by bwoolf1** [comment]
As discussed, we'll change `acp-user.sh` to assign Writer role to all services, not Manager. When the environment administrators add a service instance, they'll need to think about whether the users need broader access such as Manager, and if so configure that policy.

In a separate issue, we can modify the Terraform scripts for installing services to also update the user access group with additional policies as needed.

**Comment by bwoolf1** [comment]
When we modify `acp-user.sh`, we'll also need to update some docs and diagrams that describe what users can do with services.

**Comment by bwoolf1** [comment]
https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/commit/d7c1df658082ca8140178b7f7f83e72405926e87 fixes the script.
https://github.com/ibm-garage-cloud/ibm-garage-developer-guide/commit/4e74d2a1942197e4578a55490c38e88fbaf9e801 fixes docs that describe the permissions set by the script.

**Comment by bwoolf1** [comment]
@abalasu1: You may want to look at the latest changes to the access group scripts and make corresponding changes to your own.

**Comment by abalasu1** [comment]
@bwoolf1: Thank you, I will take the latest changes.
