### ISSUE TITLE
Update CI with Tekton documentation to match current process

### ISSUE THREAD

**Issue by lsteck** [ibm-garage-cloud/planning#335]
The Setup tekton section: 
https://cloudnativetoolkit.dev/guides/continuous-integration-tekton#setup-tekton

says to install the Tasks and Pipelines into the `dev` namespace but our igc expectes them to be installed in the tools namespace.  Here is output from my `igc pipeline` command

```
No Pipelines found in tools namespace. Skipping PipelineRun creation
Install Tekton tasks and pipelines into your namespace by running: igc namespace tools --tekton
```

**Comment by seansund** [comment]
@lsteck Can you check this with the latest CLI? I think it was addressed
