### ISSUE TITLE
 igc namespace tools --tekton does not install tasks and pipelines in tools namespace

### ISSUE THREAD

**Issue by lsteck** [ibm-garage-cloud/planning#336]
When I ran the `igc pipeline` command it notified me I didn't have tasks and pipelines defined in the tools namespace and gave me the tommand to run:

```
No Pipelines found in tools namespace. Skipping PipelineRun creation
Install Tekton tasks and pipelines into your namespace by running: igc namespace tools --tekton
```

But when I ran the ` igc namespace tools --tekton` command it did not upload the tasks and pipelines to the tools namespacde.

This is in our IKS garage-dev-iks-cluster in Kedar's account.

**Comment by seansund** [comment]
`igc namespace tools --tekton` won't install the tasks. One problem is that we have an old message in the error output that directs you to do that. I think Carlos is addressing that with his Tekton changes
