### ISSUE TITLE
[Cloud Native Toolkit docs] ACID incorrect acronym 

### ISSUE THREAD

**Issue by odrodrig** [ibm-garage-cloud/planning#338]
**Describe the bug**
In the documentation for the Cloud Databases section of the [Garage Cloud Native Toolkit](https://cloudnativetoolkit.dev/programming/databases/) docs, there is a mistake in the definition of ACID database properties. Currently, it is stated as "ACID (Atomicity, Durability, Consistency, and Durability)" when it should be "ACID (Atomicity, Consistency, Isolation, and Durability)".

**To Reproduce**
1. Go to https://cloudnativetoolkit.dev/programming/databases/
2. Scroll down to the "=== Which Database Is Right For You?" section (or cmd + f and search for ACID, it's the second result)
3. See error

**Expected behavior**
The acronym should be "ACID (Atomicity, Consistency, Isolation, and Durability)".

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina 10.15.3
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 68.7.0esr (64-bit)

**Comment by bwoolf1** [comment]
@odrodrig: Thanks for reporting this error. When ibm-garage-cloud/ibm-garage-developer-guide#149 gets merged, that'll fix it.
