### ISSUE TITLE
Observability -- Pipeline Event Framework

### ISSUE THREAD

**Issue by acmthinks** [ibm-garage-cloud/planning#339]
There seems to be no good "open" answer to pipeline observability. There is no "out of the box" way to instrument a pipeline to **collect** and **organize** significant build, test, deploy, day 2 events and correlate them to a chronological history of how an idea starts as a User Story and ends up in prod as a runtime feature. There would also be a significant amount of work to connect a dashboard (like Hygeia or some other dashboard tech) to pull together a set of realtime measurements to see if we increasing our velocity and quality products coming out of pipeline.

1. Instrument the pipeline to collect significant events (merge to master, build start, lint results, code coverage results, license compliance results, unit test results, deploy to dev, etc...) and logically link these events together, with a clear delineation of who/what/where/when, providing the foundation for an e2e view of pipeline events.

2. An "app" dashboard that shows the lifeline of a feature and how it progressed (or is progressing) through the pipeline. Display some basic delivery performance metrics (like the 4 out of Accelerate): Lead Time, Deployment Frequency, MTTR, Change Fail %.

**Comment by csantanapr** [comment]
duplicate of #50 ?

**Comment by acmthinks** [comment]
Duplicate of #50

**Comment by bwoolf1** [comment]
@acmthinks: Having closed this issue, rather than lose your comments, I think it'd be helpful if you merged your thoughts into #50.
