### ISSUE TITLE
Carlos wants to install the Toolkit on an existing OpenShift VPC2 cluster

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#403]
After manually creating an OpenShift VPC2 cluster, you should be able to install the toolkit on top of it.

**Comment by seansund** [comment]
This is currently blocked by IBM-Cloud/terraform-provider-ibm#1528

**Comment by seansund** [comment]
IBM-Cloud/terraform-provider-ibm#1528 has been addressed. A new version of the cli-tools (v0.3.0 and v0.3.1-lite) has been released with v1.7.1

**Comment by mjperrins** [comment]
Next challenge is getting Schematics team to update schematics with 1.7.1 !! for Schematics and Private Catalog Tile support
