### ISSUE TITLE
Iteration Zero won't run in OCP 4.3 cluster in VPC Gen 2: Error retrieving alb's

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#412]
**Describe the bug**
Iteration Zero scripts crash with two errors: Error retrieving alb's and Error downloading the cluster config. This looks similar to issue #32, except in this case the scripts are not creating the cluster.

**To Reproduce**
1. Create a OCP 4.3 cluster in a VPC Gen 2
2. Configure `credentials.properties` and `environment.tfvars`. Key settings in `environment.tfvars` (among others):
```
cluster_type="ocp4"
cluster_exists="true"
vpc_cluster="true"
cluster_name="sandbox-team-one-ocp43"
```
3. Run `./launch.sh` and `./runTerraform.sh`
4. Terraform output:
```
module.dev_cluster.null_resource.create_registry_namespace: Still creating... [10s elapsed]
module.dev_cluster.null_resource.create_registry_namespace: Creation complete after 11s [id=1622479046418137538]
module.dev_cluster.data.local_file.registry_url: Refreshing state...

Error: Error retrieving alb's of the cluster sandbox-team-one-ocp43: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"5a4d2a2157aa0dda-IAD","code":"E3918","description":"This operation is not supported for your cluster's version.","type":"General"}

  on .terraform/modules/dev_cluster/main.tf line 100, in data "ibm_container_vpc_cluster" "config":
 100: data "ibm_container_vpc_cluster" "config" {



Error: Error downloading the cluster config [sandbox-team-one-ocp43]: Could not login to openshift account

  on .terraform/modules/dev_cluster/main.tf line 109, in data "ibm_container_cluster_config" "cluster":
 109: data "ibm_container_cluster_config" "cluster" {


bash-4.4$ 
```

**Expected behavior**
The Developer Environment should have been installed in the existing cluster. Instead, it looks like the script died before installing anything in the cluster or creating any services.

**Screenshots**
n/a

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [X] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**

**Additional context**

**Comment by bwoolf1** [comment]
Related to #403

**Comment by seansund** [comment]
This appears to be an issue with the APIKEY. Can you try logging in from the command-line with the apikey?

```
ibmcloud login --apikey {API_KEY}
```
and
```
oc login -u apikey -p {API_KEY} {SERVER_URL}
```

you can get the SERVER_URL by running `ibmcloud ks cluster get --cluster {CLUSTER_NAME}`. The value will be the master url or public service endpoint url.
