### ISSUE TITLE
Need to configure cluster RBAC with the right access group

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#430]
Cluster RBAC is configured by running the `./terraform/scripts/rbac.sh {ACCESS-GROUP}` script. Which access group should the parameter be? [Configure Environment](https://cloudnativetoolkit.dev/admin/config-install) (which was written rather hastily and hasn't been maintained much) says to specify the admin group (i.e. `{resource_group }-ADMIN`), but that doesn't seem to work correctly. Is `rbac-roles.yaml` for the users, so the script should be run for the user group (i.e. `{resource_group }-USER`)?

**Comment by bwoolf1** [comment]
Let me know who the script is intended to configure and I can fix the docs.

**Comment by bwoolf1** [comment]
Relates to #423.

**Comment by mjperrins** [comment]
Yes the script is for Users ( Developers ) , not for Admins, Developers should have restricted access to a namespace/project and the project team working in the namespace and add more developers as they see fit , they should be able install operators from Operator Hub, and Red Hat Marketplace if that has been integrated
