### ISSUE TITLE
offering.sh fails in IBM Cloud Shell

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#431]
When you run [offering.sh](https://github.com/ibm-garage-cloud/cloudnative-toolkit/blob/master/offering.sh) in IBM Cloud Shell, you get this error:
```
$ ./offering.sh {API_KEY} "Team Catalog"
IBM Cloud Private Catalog Offering Creation!
This will create a CNCF DevOps Cloud Native Toolkit Tile in an existing Catalog
Retrieving Catalogs
./offering.sh: 66: ./offering.sh: [[: not found
Catalog does not exist, please create one with the IBM Console->Manage->Catalogs view
```

**Comment by bwoolf1** [comment]
Looks like the script uses bash commands but runs in an sh shell.

**Comment by mjperrins** [comment]
Did you fix this with the bash reference ?

**Comment by seansund** [comment]
This should be fixed now. I ran this from the cloud shell yesterday. @bwoolf1 can you test again?
