### ISSUE TITLE
Multiple releases of Tekton Pipelines in an environment needs to work better

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#433]
The [ibm-garage-tekton-tasks readme](https://github.com/IBM/ibm-garage-tekton-tasks/blob/master/README.md) explains how to install the tasks and pipelines for a release (such as v1.23.0), typically the latest release. However, if the environment already contains pipelines for another (e.g. older) release, there's no instructions for how to remove those.

If the environment contains multiple releases of the pipelines, the `oc pipeline` command lists duplicate pipelines with different versions. It's too easy for the user to accidentally choose an older version they probably shouldn't be using. It should only list the latest versions, maybe those are the only ones that should be loaded in the environment.

We need to document how to remove old versions from the environment. Better yet, `oc pipeline` should only list the latest version of each pipeline, with an optional parameter to list all available versions.

**Comment by seansund** [comment]
From v1.24.0 and up of the tekton tasks, the Pipeline resources will not include the version number in the name. That means when the tekton tasks release is installed with `kubectl apply` the Pipelines will be replaced with the latest version

**Comment by seansund** [comment]
The tekton tasks and pipelines are just kubernetes resources so to delete all of the existing pipelines you would just do `kubectl delete pipeline -n tools`.

If you wanted to just delete a specific version you would do `kubectl delete pipeline -n tools -l version=1.23.0`
