### ISSUE TITLE
Problems with latest iteration zero install

### ISSUE THREAD

**Issue by abalasu1** [ibm-garage-cloud/planning#442]
1) Latest iteration zero install fail with the following error:
Error: Error running command ‘.terraform/modules/dev_tools_argocd/scripts/deploy-instance.sh ocp4 tools appdev-cloudnativ-734219-3b1fc50af0b2002f0241bdf5d2432efd-0000.us-east.containers.appdomain.cloud argocd’: exit status 1. Output: Applying argocd instance config:
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  dex:
    image: quay.io/ablock/dex
    openShiftOAuth: true
    version: openshift-connector
  rbac:
    defaultPolicy: ‘role:readonly’
    policy: |
      g, system:cluster-admins, role:admin
    scopes: ‘[groups]’
  server:
    route: true
The ArgoCD “argocd” is invalid: spec.server.route: Invalid value: “boolean”: spec.server.route in body must be of type object: “boolean

2) argocd install using the operator in the latest toolkit cannot be used. argocd runs and the console can be accessed, but you cannot create apps, repositories, ...

Fix:
Edit the argocd instance in tools namespace and make the default policy admin.

oc edit argocd argocd -n tools

change
rbac:
defaultPolicy: role:readonly

to

rbac:
defaultPolicy: role:admin

to fix the problem.

3) When you install toolkit the default tekton url in the dashboard is wrong. It should be:
https://tekton-dashboard-tekton-pipelines.appdev-cloudnative-ocp43-6fb0b86391cd68c8282858623a1dddff-0000.eu-gb.containers.appdomain.cloud/

4) openshift pipeline url points to projects. it can be changed to https://console-openshift-console.appdev-cloudnative-ocp43-6fb0b86391cd68c8282858623a1dddff-0000.eu-gb.containers.appdomain.cloud/k8s/all-namespaces/tekton.dev~v1alpha1~Pipeline

**Comment by seansund** [comment]
This is really 4 separate issues in this bug. Can you split this up?

**Comment by seansund** [comment]
Issue 2 is already captured in ibm-garage-cloud/ibm-garage-iteration-zero#102 . As I mentioned in that issue, I don't agree with your assessment that everyone should be made admin by default

**Comment by seansund** [comment]
Issue 1 is being addressed here - ibm-garage-cloud/ibm-garage-iteration-zero#102  Finalizing testing now
