### ISSUE TITLE
Issues with console links setup for iteration zero install

### ISSUE THREAD

**Issue by abalasu1** [ibm-garage-cloud/planning#446]
Latest version of iteration zero install, terminates with the following errors:

Error: ConsoleLink.console.openshift.io "toolkit-dashboard" is invalid: spec.href: Invalid value: "": spec.href in body should match '^https://'

  on .terraform/modules/dev_tools_dashboard/main.tf line 58, in resource "helm_release" "dashboard-config":
  58: resource "helm_release" "dashboard-config" {

Error: ConsoleLink.console.openshift.io "toolkit-apieditor" is invalid: spec.href: Invalid value: "": spec.href in body should match '^https://'

  on .terraform/modules/dev_tools_swagger/main.tf line 72, in resource "helm_release" "apieditor-config":
  72: resource "helm_release" "apieditor-config" {

**Comment by seansund** [comment]
These issues have been addressed
