### ISSUE TITLE
Members of the USER access group cannot launch Logging and Monitoring dashboards from the cluster overview

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#475]
Even though users have permissions to open the LogDNA and Sysdig dashboards, the cluster overview page doesn't display Launch buttons for Logging and Monitoring.

If a user (member of the USER access group, created by the terraform/scripts/acp-user.sh script) can open the Sysdig dashboard, the Monitoring section of the cluster overview should display the Launch button. Likewise, if they can open the LogDNA dashboard, the Logging section should display the Launch button.

**Comment by bwoolf1** [comment]
The Launch buttons in the cluster overview are only displayed when the user has Administrator and Manager roles on Kubernetes service. This is a bug.

**Comment by bwoolf1** [comment]
Have opened support case #CS1908355 to get this fixed.

**Comment by bwoolf1** [comment]
Support says this is working as designed. I claim these permissions don't make sense, but they're not worried about that. They suggest that if I don't like the current behavior, I request an enhancement.

**Comment by seansund** [comment]
No longer relevant
