### ISSUE TITLE
Incorrect code coverage report in SonarQube for Spring Boot project

### ISSUE THREAD

**Issue by chobdayIbm** [ibm-garage-cloud/planning#5]
**Describe the bug**
The code coverage of automated tests is reported wrongly, as it is reported as 0% whereas there are unit tests which give a local coverage of 93%.

**To Reproduce**
1. Clone the code in https://github.com/mooc-team-three/inventory-management-svc-cdh . 
2. Run unit tests using 
`./gradlew test`
3. Open `build/reports/jacoco/test/html/index.html`.  The code coverage is 93%
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/26952482/69688052-e8ffbb00-10ff-11ea-9316-f40232529668.png">
4. Go to the pipeline at  https://jenkins-dev-cdh.mooc-three-rhos-cluster-0143c5dd31acd8e030a1d6e0ab1380e3-0001.jp-tok.containers.appdomain.cloud/job/dev-cdh/job/dev-cdh-mooc-team-three.inventory-management-svc-cdh .  A *sonar scan* is performed when the pipeline runs.
5. Go to the sonarQube project at https://sonarqube.mooc-three-rhos-cluster.jp-tok.containers.appdomain.cloud/dashboard?id=dev-cdh-mooc-team-three.inventory-management-svc-cdh .  
6. See that the coverage is reported as 0.0%.  
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/26952482/69688340-bf935f00-1100-11ea-8746-548acbcf05dc.png">

**Expected behavior**
The code coverage reported in SonarQube should not be 0%, but should be 93%, same as reported in Step 3.

**Screenshots**
(Attached to steps)

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [X] Jenkins
- [ ] Tekton
- [X] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: macOS Catalina v10.15.1
 - Browser: Safari v13.0.3

**Additional context**

**Comment by lsteck** [comment]
Currently the command in the JenkinsFile 'Test' stage is `./gradlew testClasses --no-daemon` which does not generate the coverage reports.

Updated the Test stage to use command `./gradlew test --no-daemon` which does generate coverage reports.

**Comment by lsteck** [comment]
Issue still persists in SonarQube running on our cluster.  When the 'Sonar scan' stage command runs in the Jenkins pipeline
`./gradlew -Dsonar.login=${SONARQUBE_USER} -Dsonar.password=${SONARQUBE_PASSWORD} -Dsonar.host.url=${SONARQUBE_URL} sonarqube
`
The  coverage report info does not display in SonarQube.

If I run this command locally on my mac pointing to SonarQube running locally it shows coverage information
`./gradlew -Dsonar.login=admin -Dsonar.password=admin -Dsonar.host.url=http://localhost:9000/ sonarqube`

If I run this command locally on my mac pointing to SonarQube in the cluster it does not show coverage info.
`./gradlew -Dsonar.login=admin -Dsonar.password=admin -Dsonar.host.url=http://sonarqube.mooc-one-iks-cluster.us-east.containers.appdomain.cloud/ sonarqube`

The other SonarQube information is displayed just fine.

I even tried adding additional properties to see if it would help but it doesn't.
`./gradlew -Dsonar.login=admin -Dsonar.password=admin -Dsonar.host.url=http://sonarqube.mooc-one-iks-cluster.us-east.containers.appdomain.cloud/ -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml -Dsonar.sources=src/main/java -Dsonar.jacoco.reportPath=build/jacoco/test.exec -Dsonar.junit.reportsPath=build/test-results/test -Dsonar.java.test.binaries=build/classes/java/test -Dsonar.java.binaries=build/classes/java/main -Dsonar.binaries=build/classes sonarqube`

Looks like issue with SonarQube running in our clusters.  We have version 7.8 running in the clusters and that is the version I'm running locally without problems.

**Comment by seansund** [comment]
I had to rebuild the Spring Boot Code Pattern from the ground up to get this to work. Something was fouled up in our gradle config and I couldn't figure it out otherwise
