### ISSUE TITLE
Installation on ROKS 4.5 having issue with PVC provision with API not found and Artifactory fails to come up

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#517]
**Describe the bug**
Installation on ROKS 4.5 having issue with PVC provision with API not found and Artifactory fails to come up

The following error is listed when you try and install the Toolkit on 4.5 OCP ROKS.

```
(combined from similar events): failed to provision volume with StorageClass "ibmc-vpc-block-10iops-tier": rpc error: code = Internal desc = {RequestID: e0f6938b-d53e-4c9f-bff9-378c3f825cf5 , Code: InternalError, Description: Internal error occurred, BackendError: {Code:AuthenticationFailed, Type:Unauthenticated, Description:Failed to authenticate the user., BackendError:IAM token exchange request failed: The specified API key could not be found., RC:400}, Action: Please check 'BackendError' tag for more details}
```

**To Reproduce**
1. Install Private Catalog Tile
2. Install Toolkit into 4.5 Cluster

**Expected behavior**
Artifactory is failing to install, because of this error 

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [X] Artifactory
- [ ] IBM Image Registry

**Comment by seansund** [comment]
I don't believe this is an issue with the Toolkit per se but indicates a larger issue

**Comment by seansund** [comment]
This was an issue with storage in the cluster and not anything to do with the Toolkit per se
