### ISSUE TITLE
Incorrect SonarQube & Artifactory while running "oc "

### ISSUE THREAD

**Issue by RamyaRaghuveera** [ibm-garage-cloud/planning#518]
**Describe the bug**
With the new version of toolkit and igc,running "oc credentials" command is giving incorrect URLs for Sonarqube & Artifactory.

**To Reproduce**
1. Login to oc on your terminal
2. Run "oc credentials" command
3. Check the details for Sonarqube & Artifactory.

**Expected behavior**
SonarQube & Artifactory URLs should be the URLs through which these tools can be accessed as given in "Developer Dashboard"

**Screenshots**
<img width="955" alt="Screenshot 2020-09-10 at 6 31 45 PM" src="https://user-images.githubusercontent.com/16119907/92768708-e41da680-f3b5-11ea-8093-ac3218253289.png">

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser : chrome,

**Comment by seansund** [comment]
The most recent releases of the Artifactory and SonarQube modules have added the internal service url to the `xxx-access` secret for each tool to be used within the pipeline. The external url is still stored in the `xxx-config` config map. Apparently the CLI is overwriting the value from the config map with the value from the secret. Should be a simple fix...

**Comment by seansund** [comment]
This was address with #579
