### ISSUE TITLE
Tekton deploy task does not handle hashes that contain an "e" properly

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#578]
If the hash happens to have an "e" in it (e.g. '1234e5') then when the value is written to the values.yaml and the helm chart is applied, the value gets converted into "1.234e+08".

When the tag is written to values.yaml the value should be wrapped in quotes.

**Comment by csantanapr** [comment]
Fix by https://github.com/IBM/ibm-garage-tekton-tasks/pull/70
