### ISSUE TITLE
Maureen sees a dashboard that has been updated for OpenShift 4.3

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#58]
Update the Cloud Native Toolkit Dashboard with the following updates:
- [x] move card definitions to server-side JSON
- [x] Add all strings and encoded image into JSON
- [x] Change the Card layout to be driven off `configMap` variables with JSON list been know supported tools, but the `configMap` drives the layout
- [x] dynamic tools layout (card flow) and support JSON metadata
- [x] update dashboard activation links to support new activation model
- [x] update `Starter Kit` tab to `Code Pattern ...` add new Code Patterns
- [x] change repo name to remove `catalyst`
- [x] add IBM Cloud Code Patterns into dashboard for use with `igc enable`
- [x] remove Kabanaro branding
- [x] Suport OCP 4.3 cluster version to handle new URL link behaviours between 3.11 and 4.3 and standard IKS

**Comment by mjperrins** [comment]
@bwoolf1 can we have chat about the newer activation links model I have started to experiment with ? and see if we can agree on the links that are stale , ether to remove them or final alternatives

**Comment by mjperrins** [comment]
@seansund docker hub is building v1.0.21 build off mater branch once that is complete we can do some integration testing with iZero, I will work on the Dev Guide Docs to explain the flexibility of adding tools etc.
