### ISSUE TITLE
Chore: Pass OpenShift version into the dashboard (point release number, e.g. 3.11, 4.3)

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#59]
Addressed with:

https://github.com/ibm-garage-cloud/garage-terraform-modules/pull/16

**Comment by lsteck** [comment]
@seansund For this I'm planning on adding `cluster_version` variable in the `environment.tfvars` for the user to define the version to install.  Sound good?

**Comment by seansund** [comment]
For the latest script, the cluster_type can be set to `ocp3`, `ocp4`, or `openshift` (which currently defaults to the `ocp3` behavior). During the cluster config step we create a configmap that contains a cluster_type which is always set to `openshift` without the version for backward compatibility. 

We could have a cluster_version field in the configmap that gets populated with the value reported for the cluster version (e.g. `4.3_1504`). We probably don't need to pass that in the environment.tfvars but can read it from the cluster.

Take a look at this file in the ibmcloud module - https://github.com/ibm-garage-cloud/garage-terraform-modules/blob/ocp43/cloud-managed/cluster/ibmcloud/main.tf

That's where we read the value from the cluster and create the configmap.

**Comment by mjperrins** [comment]
@lsteck can we agree on the variable name that will ba added ? can we go for something like `CLUSTER_VERSION` ? I can then complete the changes on the Dashboard if that is going to exist. 

Secondly when you get this issues resolved can you let me know what the exact versions strings are going to be

**Comment by seansund** [comment]
> @lsteck can we agree on the variable name that will ba added ? can we go for something like `CLUSTER_VERSION` ? I can then complete the changes on the Dashboard if that is going to exist.
> 
> Secondly when you get this issues resolved can you let me know what the exact versions strings are going to be

@mjperrins The implementation @lsteck has done adds `CLUSTER_VERSION` to the ibmcloud-config ConfigMap. That means CLUSTER_VERSION will be available in the dashboard pod as an environment variable.

The version number will be formatted in the way the IBM Cloud cli reports the version in `ibmcloud ks cluster get --cluster={cluster name}`
- IKS: `1.15.8_1529`
- OCP3: `3.11.161_1539_openshift`
- OCP4: `4.3.0_1507_openshift`

**Comment by lsteck** [comment]
@mjperrins @seansund 

Yes it will be in the environment variable CLUSTER_VERSION but it will only contain the point release, so for example:

- IKS: 1.15
- OCP3: 3.11
- OCP4: 4.3
