### ISSUE TITLE
GraphQL Typescript image is not clean

### ISSUE THREAD

**Issue by chobdayIbm** [ibm-garage-cloud/planning#6]
**Describe the bug**
In Vulnerability Advisor in IBM Cloud Registry, 5 mySql vulnerabilities are flagged, when the image should be clean.

**To Reproduce**
1. Go to https://cloud.ibm.com/kubernetes/registry/images/mooc-team-three/inventory-management-bff-cdh/sha256:40651538fdafbd05364a31103a17295b09bef12070dde56d994850d088e90593/detail/issues?region=ap-north
2. Scroll down to 'Configuration Issues'
4. See that there are five issues.
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/26952482/69688961-84922b00-1102-11ea-9cab-4add1643d25b.png">

**Expected behavior**
These 5 issues should not be there, because the code does not even make use of mySql.  

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ ] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [X] IBM Image Registry

**Desktop (please complete the following information):**
OS: macOS Catalina v10.15.1
Browser: Safari v13.0.3

**Additional context**
The code can be found at https://github.com/mooc-team-three/inventory-management-bff-cdh .   
It is a GraphQL Typescript project, based on https://github.com/ibm-garage-cloud/template-graphql-typescript
I don't know of any mySql code inside.

**Comment by seansund** [comment]
This is a dup of https://github.com/ibm-garage-cloud/template-graphql-typescript/issues/5
