### ISSUE TITLE
Specifying a storage class for artifcatory module doesn't get correctly applied

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/planning#609]
**Describe the bug**
Specifying a storage class for artifcatory module doesn't get correctly applied

**To Reproduce**
Specify `storage_class` for artifactory module, the storage Class Name for the PVC created for the artifactory statefulset is not configured with the specify Class taking the default class configured for autoprovisioning

**Expected behavior**

**Screenshots**

**IBM Cloud**
Select the services and tools affected
- [x] Red Hat OpenShift Managed Services
- [x] Artifactory

This was discovered by @jpapejr

**Comment by csantanapr** [comment]
@jpapejr give it a try again
Setting the configmap with `storage_class`  in quick install should work now.
cc @seansund

**Comment by csantanapr** [comment]
Use the latest code from master in iteration zero https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/pull/228

**Comment by jpapejr** [comment]
Works with new `storage_class`  option defined in the configmap. I've got Artifactory on `ocs-storagecluster-ceph-rbd` just like I wanted.. Thanks!

**Comment by csantanapr** [comment]
Thank you for verifying the defect @jpapejr
