### ISSUE TITLE
Maureen wants a starter kit and pipeline for a Quarkus-based application

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#651]

**Comment by lsteck** [comment]
@seansund @csantanapr 

Here is a link to the [template-quarkus](https://github.com/ibm-garage-cloud/template-quarkus) let me know what you think.

How do I get this pushed to the IBM org?

**Comment by lsteck** [comment]
Add this to the 

- workshop
- dashboard
- website

**Comment by seansund** [comment]
To add the starter kit to the dashboard, add the repo to the codepatterns section of the config file https://github.com/ibm-garage-cloud/developer-dashboard/blob/main/public/data/links.json
