### ISSUE TITLE
git webhook created with http instead of https

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/planning#689]
when running `oc pipeline ${GIT_URL}`

When prompted for image scan and answer No/n

The CLI creates the webhook on the github (public) with `http` back to the route on the OpenShift cluster

Expected the URL to the OpenShift route to be `https`

When selecting scan image Yes/y then the webhook is created with `https` correctly

**Comment by csantanapr** [comment]
@bwoolf1 this is the issue you reported on Slack

**Comment by csantanapr** [comment]
It looks like the problem is not the scanning parameter

It looks like the first time the trigger deployment is created the cli checks the route `https` and is not ready and falls back to `http`
https://github.com/ibm-garage-cloud/ibm-garage-cloud-cli/blob/main/src/services/register-pipeline/register-tekton-pipeline.ts#L292-L301

**Comment by csantanapr** [comment]
subsequent pipelines using the same trigger will use https

**Comment by seansund** [comment]
We need to check the status of the Trigger and Route deployment before checking the health. We also should be smarter about determining https vs http by looking at the route configuration. Right now we try https then failover to http...
