### ISSUE TITLE
Toolkit Install failing with dockerhub rate limit

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/planning#703]
An user trying the new Workshops https://cloudnativetoolkit.dev/workshop/setup

Reported a dockerhub limit error on Toolkit install

```
module.dev_tools_artifactory.helm_release.artifactory[0]: Still creating... [17m30s elapsed]
module.dev_tools_sonarqube.null_resource.wait-for-config-job[0]: Still creating... [15m20s elapsed]
```

```
Failed to pull image "ibmgaragecloud/nodejs:latest": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/ibmgaragecloud/nodejs: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by jpapejr** [comment]
Pulls eventually did finish but took much longer than anticipated.

**Comment by csantanapr** [comment]
Sorry about that @jpapejr  and thank you ❤️ for being a good citizen by reporting the problem

**Comment by csantanapr** [comment]
This is now fixed on master and quick install @jpapejr 
https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/pull/282

I will leave open until we cut a release of iteration zero

**Comment by csantanapr** [comment]
Latest release of iteration zero has the fixed
https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/releases/tag/v2.10.0
