### ISSUE TITLE
Workshop scripts pulling from master branch instead of main.

### ISSUE THREAD

**Issue by lsteck** [ibm-garage-cloud/planning#755]
Developer-dashboard is now using main as default branch so changes are going there.  Need to update the scripts to pull from there instead of master.

For example in **20-toolkit-dashboard.sh**
`ORGINAL_JSON_URL=${ORGINAL_JSON_URL:-https://raw.githubusercontent.com/ibm-garage-cloud/developer-dashboard/master/public/data/links.json}`

**Comment by lsteck** [comment]
@csantanapr I see there are other references to master that we should probably discuss, for now I will just change the one listed above.

**Comment by csantanapr** [comment]
Thanks for the fix @lsteck
