### ISSUE TITLE
Chore: Move `Code Patterns` into IBM git org

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#81]
Prepare transition of Startkit Templates to Code Patterns repositories for Open Source publishing to github.com/IBM account

- [x] Complete Open Source training
- [x] Create 7 repos in IBM account
- [x] Update license files
- [x] Review code for any content not suitable for external publishing
- [x] Push code to IBM account into `dev` branch
- [x] Document links and share
- [x] Coordinate release with milestone release

Move the following repositories to the public IBM account

- [x] `template-node-react`
- [x] `template-node-angular`
- [x] `template-graphql-typescript`
- [x] `template-node-typescript`
- [x] `template-java-spring`
- [x] `template-argocd-gitops`
- [x] `template-ibmcloud-services`

Here are the instructions for creating repos in the github.org/IBM account

Hi Matthew-

Sure, here's the link for info on contributing:
https://w3.ibm.com/developer/opensource/contribute/contributions/

And also for getting the repos setup in the IBM GitHub org once you have all your approvals:
https://w3.ibm.com/developer/opensource/contribute/ibm-github/

Let me know if you have any other questions,

Jennifer Skeivik - jennifer.skeivik@us.ibm.com jennifer.skeivik@us.ibm.com

**Comment by mjperrins** [comment]
Here are the instructions for creating repos in the github.org/IBM account

Hi Matthew-
 
Sure, here's the link for info on contributing:
https://w3.ibm.com/developer/opensource/contribute/contributions/
 
And also for getting the repos setup in the IBM GitHub org once you have all your approvals:
https://w3.ibm.com/developer/opensource/contribute/ibm-github/
 
Let me know if you have any other questions,
 
Jennifer Skeivik - jennifer.skeivik@us.ibm.com <jennifer.skeivik@us.ibm.com>

**Comment by seansund** [comment]
Need to look at redoing this as a `repo move`
