### ISSUE TITLE
Dashboard route not working on branch ocp43 install on OCP 3.11

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#94]
Dashboard route not working on branch ocp43 install on OCP 3.11

After install, both `igc dashboard` and clicking on the route dont work, even when the pod is running and logs are clean, this is happening on OCP 3.11 install off the OCP43 branch

**Comment by mjperrins** [comment]
Is this part of the issue to do with side car oauth ?

**Comment by seansund** [comment]
Is this still a problem? Feels like this was fixed
